apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "travelmind-ai.fullname" . }}
  labels: {{- include "travelmind-ai.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: prod
  MANAGEMENT_PORT: "9090"
  MYSQL_HOST: {{ .Values.config.mysqlHost | quote }}
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.config.mysqlUser | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  RABBITMQ_HOST: {{ .Values.config.rabbitmqHost | quote }}
  RABBITMQ_USERNAME: {{ .Values.config.rabbitmqUsername | quote }}
  ELASTICSEARCH_URIS: {{ .Values.config.elasticsearchUris | quote }}
  PGVECTOR_JDBC_URL: {{ .Values.config.pgvectorJdbcUrl | quote }}
  PGVECTOR_USERNAME: {{ .Values.config.pgvectorUsername | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
  OTEL_TRACES_SAMPLER_PROBABILITY: {{ .Values.config.traceSamplingProbability | quote }}
  USER_MAP_TOOL_QPS: {{ .Values.config.userMapToolQps | quote }}
