CREATE TABLE IF NOT EXISTS `agent_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `request_id` VARCHAR(128) NOT NULL,
    `user_id` BIGINT NULL,
    `conversation_id` VARCHAR(128) NOT NULL,
    `task_type` VARCHAR(32) NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `workflow_version` VARCHAR(32) NOT NULL,
    `current_node` VARCHAR(64) NULL,
    `request_json` JSON NOT NULL,
    `result_json` LONGTEXT NULL,
    `error_code` VARCHAR(64) NULL,
    `error_message` VARCHAR(1024) NULL,
    `cancel_requested` TINYINT NOT NULL DEFAULT 0,
    `model_calls_used` INT NOT NULL DEFAULT 0,
    `tokens_used` INT NOT NULL DEFAULT 0,
    `node_executions_used` INT NOT NULL DEFAULT 0,
    `version` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `started_at` DATETIME(3) NULL,
    `finished_at` DATETIME(3) NULL,
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agent_task_request_id` (`request_id`),
    KEY `idx_agent_task_status_updated` (`status`, `updated_at`),
    KEY `idx_agent_task_user_created` (`user_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent异步任务事实表';

CREATE TABLE IF NOT EXISTS `agent_workflow_checkpoint` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `task_id` BIGINT NOT NULL,
    `node_id` VARCHAR(64) NOT NULL,
    `node_version` VARCHAR(32) NOT NULL,
    `attempt` INT NOT NULL,
    `node_status` VARCHAR(32) NOT NULL,
    `input_snapshot` LONGTEXT NULL,
    `output_snapshot` LONGTEXT NULL,
    `state_snapshot` LONGTEXT NULL,
    `started_at` DATETIME(3) NOT NULL,
    `finished_at` DATETIME(3) NULL,
    `error_type` VARCHAR(64) NULL,
    `error_message` VARCHAR(1024) NULL,
    `retryable` TINYINT NOT NULL DEFAULT 0,
    `duration_ms` BIGINT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_checkpoint_task_node_attempt` (`task_id`, `node_id`, `attempt`),
    KEY `idx_checkpoint_task_status` (`task_id`, `node_status`),
    CONSTRAINT `fk_checkpoint_task` FOREIGN KEY (`task_id`) REFERENCES `agent_task` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent工作流检查点';

CREATE TABLE IF NOT EXISTS `outbox_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `event_id` VARCHAR(64) NOT NULL,
    `aggregate_type` VARCHAR(64) NOT NULL,
    `aggregate_id` VARCHAR(64) NOT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `routing_key` VARCHAR(128) NOT NULL,
    `payload_json` JSON NOT NULL,
    `status` VARCHAR(24) NOT NULL,
    `retry_count` INT NOT NULL DEFAULT 0,
    `next_retry_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `last_error` VARCHAR(1024) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `published_at` DATETIME(3) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_outbox_event_id` (`event_id`),
    KEY `idx_outbox_publish` (`status`, `next_retry_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='事务消息Outbox';
